# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_default', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PhraseAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.TextField()),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='grammar_text.Phrase')),
            ],
        ),
        migrations.CreateModel(
            name='PhraseParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('integer', 'число'), ('time', 'время'), ('date', 'дата'), ('date_time', 'дата и время'), ('regexp', 'регулярное выражение')], max_length=50)),
                ('params', models.TextField(help_text='JSON')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='grammar_text.Phrase')),
            ],
        ),
    ]
