# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar_text', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phrase',
            options={'ordering': ('is_default', 'text')},
        ),
        migrations.AlterField(
            model_name='phraseparam',
            name='params',
            field=models.TextField(blank=True, help_text='JSON'),
        ),
        migrations.AlterField(
            model_name='phraseparam',
            name='type',
            field=models.CharField(choices=[('string', 'строка'), ('integer', 'число'), ('time', 'время'), ('date', 'дата'), ('date_time', 'дата и время'), ('regexp', 'регулярное выражение')], max_length=50),
        ),
    ]
